/*
 * STACKIT DNS API
 *
 * This api provides dns
 *
 * API version: 1.0
 * Contact: stackit-dns@mail.schwarz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Zone to create.
type ZoneZonePost struct {
	// access control list
	Acl string `json:"acl,omitempty"`
	// contact e-mail for the zone
	ContactEmail string `json:"contactEmail,omitempty"`
	// default time to live
	DefaultTTL int32 `json:"defaultTTL,omitempty"`
	// description of the zone
	Description string `json:"description,omitempty"`
	// zone name
	DnsName string `json:"dnsName"`
	// expire time
	ExpireTime int32 `json:"expireTime,omitempty"`
	// if the zone is a reverse zone or not
	IsReverseZone bool `json:"isReverseZone,omitempty"`
	// user given name
	Name string `json:"name"`
	// primary name server for secondary zone
	Primaries []string `json:"primaries,omitempty"`
	// primary name server. FQDN
	PrimaryNameServer string `json:"primaryNameServer,omitempty"`
	// refresh time
	RefreshTime int32 `json:"refreshTime,omitempty"`
	// retry time
	RetryTime int32 `json:"retryTime,omitempty"`
	// zone type
	Type_ string `json:"type,omitempty"`
}
