/*
 * STACKIT DNS API
 *
 * This api provides dns
 *
 * API version: 1.0
 * Contact: stackit-dns@mail.schwarz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DomainUpdateZone struct {
	// access control list
	Acl string `json:"acl,omitempty"`
	// contact e-mail for the zone
	ContactEmail string `json:"contactEmail,omitempty"`
	// default time to live
	DefaultTTL int32 `json:"defaultTTL,omitempty"`
	// description of the zone
	Description string `json:"description,omitempty"`
	// expire time
	ExpireTime int32 `json:"expireTime,omitempty"`
	// user given name
	Name string `json:"name"`
	// refresh time
	RefreshTime int32 `json:"refreshTime,omitempty"`
	// retry time
	RetryTime int32 `json:"retryTime,omitempty"`
}
