/*
 * STACKIT DNS API
 *
 * This api provides dns
 *
 * API version: 1.0
 * Contact: stackit-dns@mail.schwarz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// RRSetPatch for rr patch set info.
type RrsetRrSetPatch struct {
	// user comment
	Comment string `json:"comment,omitempty"`
	// rfc1035 Section 2.3.4
	Name string `json:"name,omitempty"`
	// records
	Records []RrsetRecordPost `json:"records,omitempty"`
	// time to live
	Ttl int32 `json:"ttl,omitempty"`
}
