/*
 * STACKIT DNS API
 *
 * This api provides dns
 *
 * API version: 1.0
 * Contact: stackit-dns@mail.schwarz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ResponseZone for user info.
type ZoneResponseZone struct {
	Message string `json:"message,omitempty"`
	Zone *DomainZone `json:"zone"`
}
