/*
 * STACKIT DNS API
 *
 * This api provides dns
 *
 * API version: 1.0
 * Contact: stackit-dns@mail.schwarz
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// ResponseRRSetAll.
type RrsetResponseRrSetAll struct {
	ItemsPerPage int32 `json:"itemsPerPage"`
	Message string `json:"message,omitempty"`
	RrSets []DomainRrSet `json:"rrSets"`
	TotalItems int32 `json:"totalItems"`
	TotalPages int32 `json:"totalPages"`
}
