# https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  default: none
  enable: # golangci-lint help linters
    - copyloopvar # A linter detects places where loop variables are copied. https://golangci-lint.run/usage/linters/#copyloopvar
    - dogsled
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - revive
    - rowserrcheck # Checks whether Rows.Err of rows is checked successfully.
    - errorlint # Checking for unchecked errors in Go code https://golangci-lint.run/usage/linters/#errcheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - decorder # Check declaration order and count of types, constants, variables and functions. https://golangci-lint.run/usage/linters/#decorder
    - tagalign # Check that struct tags are well aligned. https://golangci-lint.run/usage/linters/#tagalign
    - predeclared # Find code that shadows one of Go's predeclared identifiers
    - sloglint # Ensure consistent code style when using log/slog
    - asciicheck  # Checks that all code identifiers does not have non-ASCII symbols in the name
    - nilnil # Checks that there is no simultaneous return of nil error and an nil value. ref: https://golangci-lint.run/usage/linters/#nilnil
    - cyclop # Checks function and package cyclomatic complexity. https://golangci-lint.run/usage/linters/#cyclop
  settings:
    exhaustive:
      default-signifies-exhaustive: false
    misspell:
      locale: US
    revive:
      rules:
        - name: confusing-naming
          disabled: true
    cyclop: # Lower cyclomatic complexity threshold after the max complexity is lowered
      max-complexity: 52
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - deadcode
          - depguard
          - dogsled
          - goprintffuncname
          - govet
          - ineffassign
          - misspell
          - nolintlint
          - rowserrcheck
          - staticcheck
          - structcheck
          - unconvert
          - unused
          - varcheck
          - whitespace
        path: _test\.go
      # TODO: skiip as will require design changes
      - linters:
          - nilnil
        path: istio_virtualservice.go|fqdn.go|cloudflare.go
    paths:
      - endpoint/zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - sigs.k8s.io/external-dns
  exclusions:
    generated: lax
    paths:
      - endpoint/zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
      - _test\.go
