# https://golangci-lint.run/usage/configuration/
version: "2"
linters:
  default: none
  enable: # golangci-lint help linters
    - dogsled
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - revive
    - rowserrcheck
    - staticcheck
    - unconvert
    - unused
    - whitespace
    - predeclared # Find code that shadows one of Go's predeclared identifiers
    - sloglint # Ensure consistent code style when using log/slog
    - asciicheck  # Checks that all code identifiers does not have non-ASCII symbols in the name
  settings:
    exhaustive:
      default-signifies-exhaustive: false
    misspell:
      locale: US
    revive:
      rules:
        - name: confusing-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - deadcode
          - depguard
          - dogsled
          - goprintffuncname
          - govet
          - ineffassign
          - misspell
          - nolintlint
          - rowserrcheck
          - staticcheck
          - structcheck
          - unconvert
          - unused
          - varcheck
          - whitespace
        path: _test\.go
    paths:
      - endpoint/zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - sigs.k8s.io/external-dns
  exclusions:
    generated: lax
    paths:
      - endpoint/zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
      - _test\.go
