linters-settings:
  exhaustive:
    default-signifies-exhaustive: false
  goimports:
    local-prefixes: sigs.k8s.io/external-dns
  golint:
    min-confidence: 0.9
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - deadcode
    - depguard
    - dogsled
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - deadcode
        - depguard
        - dogsled
        - gofmt
        - goimports
        - goprintffuncname
        - gosimple
        - govet
        - ineffassign
        - misspell
        - nolintlint
        - rowserrcheck
        - staticcheck
        - structcheck
        - stylecheck
        - typecheck
        - unconvert
        - unused
        - varcheck
        - whitespace

run:
  skip-files:
    - endpoint/zz_generated.deepcopy.go
