# https://golangci-lint.run/docs/configuration/
version: "2"
linters:
  default: none
  enable: # golangci-lint help linters
    - copyloopvar # A linter detects places where loop variables are copied. https://golangci-lint.run/docs/linters/configuration/#copyloopvar
    - dogsled # Checks assignments with too many blank identifiers. https://golangci-lint.run/docs/linters/configuration/#dogsled
    - dupword # Duplicate word. https://golangci-lint.run/docs/linters/configuration/#dupword
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - revive # https://golangci-lint.run/docs/linters/configuration/#revive
    - recvcheck # Checks for receiver type consistency. https://golangci-lint.run/docs/linters/configuration/#recvcheck
    - rowserrcheck # Checks whether Rows.Err of rows is checked successfully.
    - errchkjson # Checks types passed to the json encoding functions. ref: https://golangci-lint.run/docs/linters/configuration/#errchkjson
    - errorlint # Checking for unchecked errors in Go code https://golangci-lint.run/docs/linters/configuration/#errorlint
    - staticcheck
    - unconvert
    - unused # https://golangci-lint.run/docs/linters/configuration/#unused
    - unparam # https://golangci-lint.run/docs/linters/configuration/#unparam
    - usestdlibvars # A linter that detect the possibility to use variables/constants from the Go standard library. https://golangci-lint.run/docs/linters/configuration/#usestdlibvars
    - whitespace
    - decorder # Check declaration order and count of types, constants, variables and functions. https://golangci-lint.run/docs/linters/configuration/#decorder
    - tagalign # Check that struct tags are well aligned. https://golangci-lint.run/docs/linters/configuration/#tagalign
    - predeclared # Find code that shadows one of Go's predeclared identifiers
    - sloglint # Ensure consistent code style when using log/slog
    - asciicheck  # Checks that all code identifiers does not have non-ASCII symbols in the name
    - nilnil # Checks that there is no simultaneous return of nil error and an nil value. ref: https://golangci-lint.run/docs/linters/configuration/#nilnil
    - nonamedreturns # Checks that functions with named return values do not return named values. https://golangci-lint.run/docs/linters/configuration/#nonamedreturns
    - cyclop # Checks function and package cyclomatic complexity. https://golangci-lint.run/docs/linters/configuration/#cyclop
    - gocritic # Analyze source code for various issues, including bugs, performance hiccups, and non-idiomatic coding practices. https://golangci-lint.run/docs/linters/configuration/#gocritic
    - gochecknoinits # Checks that there are no init() functions in the code. https://golangci-lint.run/docs/linters/configuration/#gochecknoinits
    - goconst # Finds repeated strings that could be replaced by a constant. https://golangci-lint.run/docs/linters/configuration/#goconst
    - modernize # A suite of analyzers that suggest simplifications to Go code, using modern language and library features. https://golangci-lint.run/docs/linters/configuration/#modernize

    # tests
    - testifylint # Checks usage of github.com/stretchr/testify. https://golangci-lint.run/docs/linters/configuration/#testifylint
  settings:
    exhaustive:
      default-signifies-exhaustive: false
    misspell:
      locale: US
    revive:
      rules:
        - name: confusing-naming
          disabled: true
        - name: unused-parameter # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md#unused-parameter
          disabled: false
    cyclop: # Lower cyclomatic complexity threshold after the max complexity is lowered
      max-complexity: 37 # Controller/execute.go:147:1: calculated cyclomatic complexity for function buildProvider is 37
    goconst:
      min-occurrences: 3
      # Ignore well-known DNS record types, boolean strings, and common values
      ignore-string-values:
        - "^(A|AAAA|ALIAS|CNAME|MX|NS|PTR|SRV|TXT)$"  # DNS record types
        - "^(true|false)$"  # Boolean strings
        - "^none$"  # Common null/empty indicator
        - "^(aws-sd|noop)$"  # Registry types - can be ignored for consistency
    testifylint:
      # Enable all checkers (https://github.com/Antonboom/testifylint#checkers).
      # Default: false
      enable-all: true
      # Disable checkers by name
      # (in addition to default
      #   suite-thelper
      # ).
      # TODO: enable in follow-up
      disable:
        - require-error
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - deadcode
          - depguard
          - dogsled
          - goprintffuncname
          - govet
          - ineffassign
          - misspell
          - nolintlint
          - rowserrcheck
          - staticcheck
          - structcheck
          - unconvert
          - varcheck
          - whitespace
          - goconst
        path: _test\.go
      # TODO: skiip as will require design changes
      - linters:
          - nilnil
        path: istio_virtualservice.go|fqdn.go|cloudflare_custom_hostnames.go
      - linters:
          - gochecknoinits
        path: ^(internal/.*/init\.go|.*/metrics\.go|.*/webhook\.go|.*/http\.go|apis/.*\.go|.*/cached_provider\.go)$
      - linters:
          - modernize
        path: ^(apis/.*\.go)$
    paths:
      - endpoint/zz_generated.deepcopy.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - sigs.k8s.io/external-dns
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go
