# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 5000s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: "gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20230206-8160eea68e"
    entrypoint: bash
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - VERSION=$_GIT_TAG
      - PULL_BASE_REF=$_PULL_BASE_REF
      - HOME=/root
    args:
      - -c
      - |
        /buildx-entrypoint version
        apk add musl-dev gcc
        make release.staging
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: "12345"
  _PULL_BASE_REF: 'master'
