# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 3000s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: "gcr.io/k8s-testimages/gcb-docker-gcloud:v20200824-5d057db"
    entrypoint: make
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
      - VERSION=$_GIT_TAG
      - PULL_BASE_REF=$_PULL_BASE_REF
    args:
      - release.staging
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: "12345"
  _PULL_BASE_REF: 'master'
