# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 5000s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'
steps:
  - name: 'docker.io/library/golang:1.21.1-bullseye'
    entrypoint: make
    env:
      - VERSION=$_GIT_TAG
      - PULL_BASE_REF=$_PULL_BASE_REF
    args:
      - release.staging
substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: "12345"
  _PULL_BASE_REF: 'master'
