# Custom values for schema creation.
# This is a YAML-formatted file.
# Declare variables to be passed into your schema.
resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 128Mi

provider:
  webhook:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 200Mi
