{{- if eq .Values.global.mode "workload" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "external-dns.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "external-dns.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
