---
openapi: "3.0.0"
info:
  version: 0.14.0
  title: External DNS Webhook Server
  description: >-
    Implements the external DNS webhook endpoints.
  contact:
    url: https://github.com/kubernetes-sigs/external-dns
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: initialization
    description: Endpoints for initial negotiation.
  - name: listing
    description: Endpoints to get listings of DNS records.
  - name: update
    description: Endpoints to update DNS records.
servers:
  - url: http://localhost:10721
    description: Server url for a k8s deployment.
paths:
  /:
    get:
      summary: >-
        Initialisation and negotiates headers and returns domain
        filter.
      description: |
        Initialisation and negotiates headers and returns domain
        filter.
      operationId: negotiate
      tags: [initialization]
      responses:
        '200':
          description: |
            The list of domains this DNS provider serves.
          content:
            application/external.dns.webhook+json;version=1:
              schema:
                $ref: '#/components/schemas/filters'
              example:
                filters:
                  - example.com
        '500':
          description: |
            Failed to provide the list of domains we serve.

  /records:
    get:
      summary: Returns the current records.
      description: |
        Get the current records from the DNS provider and return them.
      operationId: getRecords
      tags: [listing]
      responses:
        '200':
          description: |
            Provided the list of DNS records successfully.
          content:
            application/external.dns.webhook+json;version=1:
              schema:
                $ref: '#/components/schemas/endpoints'
        '500':
          description: |
            Failed to provide the list of DNS records.

    post:
      summary: Applies the changes.
      description: |
        Set the records in the DNS provider based on those supplied here.
      operationId: setRecords
      tags: [update]
      requestBody:
        description: |
          This is the list of changes that are required.

          TODO: Explain how this should be applied.
        required: true
        content:
          application/external.dns.webhook+json;version=1:
            schema:
              $ref: '#/components/schemas/changes'
      responses:
        '204':
          description: |
            Changes were accepted.
        '500':
          description: |
            Changes were not accepted.

  /adjustendpoints:
    post:
      summary: Executes the AdjustEndpoints method.
      description: |
        Adjusts the records in the provider based on those supplied here.
      operationId: adjustRecords
      tags: [update]
      requestBody:
        description: |
          This is the list of records to be adjusted.

          TODO: Explain how this should be applied.
        required: true
        content:
          application/external.dns.webhook+json;version=1:
            schema:
              $ref: '#/components/schemas/endpoints'
      responses:
        '200':
          description: |
            Adjustments were accepted.
          content:
            application/external.dns.webhook+json;version=1:
              schema:
                $ref: '#/components/schemas/endpoints'
        '500':
          description: |
            Adjustments were not accepted.

components:
  schemas:
    filters:
      description: |
        TODO: explain the filters object.
      type: object
      properties:
        filters:
          type: array
          items:
            type: string

    endpoints:
      description: |
        TODO: explain the endpoints array.
      type: array
      items:
        $ref: '#/components/schemas/endpoint'

    endpoint:
      description: |
        TODO: explain the endpoint object.
      type: object
      properties:
        dnsName:
          type: string
        targets:
          $ref: '#/components/schemas/targets'
        recordType:
          type: string
        setIdentifier:
          type: string
        recordTTL:
          type: integer
          format: int64
        labels:
          type: object
          additionalProperties:
            type: string
        providerSpecific:
          type: array
          items:
            $ref: '#/components/schemas/providerSpecificProperty'
      example:
        dnsName: foo.example.com
        recordType: A
        recordTTL: 60

    targets:
      description: |
        TODO: explain the targets array.
      type: array
      items:
        type: string
      example:
        - 1.2.3.4
        - 1.2.3.5

    providerSpecificProperty:
      description: |
        TODO: explain the provider object.  What might this be used for?
        Examples?
      type: object
      properties:
        name:
          type: string
        value:
          type: string
      example:
        name: foo
        value: bar

    changes:
      description: |
        TODO: explain the changes object.
      type: object
      properties:
        create:
          $ref: '#/components/schemas/endpoints'
        updateOld:
          $ref: '#/components/schemas/endpoints'
        updateNew:
          $ref: '#/components/schemas/endpoints'
        delete:
          $ref: '#/components/schemas/endpoints'
