name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:

  test:
    permissions:
      contents: read  #  to fetch code (actions/checkout)
      checks: write  #  to create a new check based on the results (shogo82148/actions-goveralls)

    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # tests for target OS
        os: [ubuntu-latest, macos-latest]
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Set up Go 1.x
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
      with:
        go-version-file: go.mod
        check-latest: true
      id: go

    - name: Install Dependencies
      run: |
        go get -v -t -d ./...

    - name: Test
      env:
        GOMAXPROCS: 4
        GOMEMLIMIT: 8192MiB
      run: make go-test

    - name: Send coverage
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      with:
        file: profile.cov
        format: golang
        flag-name: run-${{ join(matrix.*, '-') }}
        parallel: true
      continue-on-error: true

  finish:
    needs: test
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
      with:
        parallel-finished: true
        carryforward: "run-ubuntu-latest,run-macos-latest"
      continue-on-error: true
