name: License Check

on:
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'go.tool.mod'
      - 'go.tool.sum'

permissions:
  contents: read

jobs:
  license-check:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # https://github.com/apache/skywalking-eyes
      - name: Check dependency licenses
        uses: apache/skywalking-eyes/dependency@61275cc80d0798a405cb070f7d3a8aaf7cf2c2c1 # v0.8.0
        with:
          config: .licenserc.yaml
          mode: check
          flags: "-w"
