name: Release Chart

on:
  push:
    branches:
      - master
    paths:
      - "charts/external-dns/Chart.yaml"

permissions: {}
jobs:
  release:
    permissions:
      contents: write #  to push chart release and create a release (helm/chart-releaser-action)

    if: github.repository == 'kubernetes-sigs/external-dns'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Get chart version
        id: chart_version
        run: |
          set -euo pipefail
          chart_version="$(grep -Po "(?<=^version: ).+" charts/external-dns/Chart.yaml)"
          echo "version=${chart_version}" >> $GITHUB_OUTPUT

      - name: Get changelog entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@32aa5b4c155d76c94e4ec883a223c947b2f02656 # v2.2.3
        with:
          path: charts/external-dns/CHANGELOG.md
          version: "v${{ steps.chart_version.outputs.version }}"

      - name: Create release notes
        run: |
          set -euo pipefail
          cat <<"EOF" > charts/external-dns/RELEASE.md
          ${{ steps.changelog_reader.outputs.changes }}
          EOF

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: latest

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_RELEASE_NAME_TEMPLATE: "external-dns-helm-chart-{{ .Version }}"
          CR_RELEASE_NOTES_FILE: RELEASE.md
          CR_MAKE_RELEASE_LATEST: false
